### ISSUE TITLE
How to use for multiple domains/zone IDs?

### ISSUE THREAD

**Issue by TheMightyJonez** [hugomd/cloudflare-ddns#19]
This has been great for me! How can I have the DDNS update for two separate domains managed by cloudflare? The Zone IDs are different.

**Comment by hugomd** [comment]
I'm glad you like it! 

Just to clarify so I'm understanding correctly: you want to update two separate zones with the same IP address?

That's not supported at the moment, but I'm sure it's something we could add, possible by setting comma separated environment variables, e.g.: `CLOUDFLARE_ZONEID=abc123,def456`.

In the meantime, you could use this to update one domain with `cloudflare-ddns`, and then you could point the other domain to it with a `CNAME`.

E.g. 
`A` record for `example1.tld` to some IP (updated with DDNS)
`CNAME` record for `example2.tld` pointing to `example1.tld`

That way you only ever have to update a single zone.

**Comment by hugomd** [comment]
Closing this for now, if you have any ongoing issues feel free to reply or make a new issue 👍🏻

**Comment by silkyclouds** [comment]
Is this now implemented ? I've tried to separate mydomain.com and *.mydomain.com with a comma (,) but it's still seen as a single record. Which means its not working.

**Comment by hugomd** [comment]
> Is this now implemented ? I've tried to separate mydomain.com and *.mydomain.com with a comma (,) but it's still seen as a single record. Which means its not working.

This hasn't been implemented. I closed this issue due to inactivity.

**Comment by silkyclouds** [comment]
OK but I might have missunderstood how to achieve this. while the container updated mydomain.com without any issue, can you eventually let me know how to update the A record that is named " * "? should I run another instance of the container to do so ? and what would be the right domain to point to ? I've tried doing so and using *.mydomain.com, as well as simply *, but both fails detecting the record on my cloudflare account. Thanks ! :)
